import fs from 'fs';
import { MemoryStorage, MessageFactory, TurnContext, CardFactory } from "botbuilder";
import * as path from "path";
import config from "../config";
import { createResponseCard } from './card';
// See https://aka.ms/teams-ai-library to learn more about the Teams AI library.
import { Application, ActionPlanner, OpenAIModel, PromptManager, AI, PredictedSayCommand } from "@microsoft/teams-ai";

// Create AI components
const model = new OpenAIModel({
  azureApiKey: config.azureOpenAIKey,
  azureDefaultDeployment: config.azureOpenAIDeploymentName,
  azureEndpoint: config.azureOpenAIEndpoint,
  azureApiVersion: '2024-08-01-preview',

  useSystemMessages: true,
  logRequests: true,
});
const prompts = new PromptManager({
  promptsFolder: path.join(__dirname, "../prompts"),
});

const planner = new ActionPlanner({
  model,
  prompts,
  defaultPrompt:
    async () => {
      const template = await prompts.getPrompt('chat');
      const skprompt = fs.readFileSync(path.join(__dirname, '..', 'prompts', 'chat', 'skprompt.txt'));

      const dataSources = (template.config.completion as any)['data_sources'];

      dataSources.forEach((dataSource: any) => {
        if (dataSource.type === 'azure_search') {
          dataSource.parameters.authentication.key = config.azureSearchKey;
          dataSource.parameters.endpoint = config.azureSearchEndpoint;
          dataSource.parameters.index_name = config.indexName;
          dataSource.parameters.embedding_dependency.deployment_name = config.azureOpenAIEmbeddingDeploymentName;
          dataSource.parameters.role_information = `${skprompt.toString('utf-8')}`;
        }
      });
      return template;
    }
});

// Define storage and application
const storage = new MemoryStorage();
const app = new Application({
  storage,
  ai: {
    planner,
    //feedback loop is enabled
    enable_feedback_loop: true
  },
});

app.feedbackLoop(async (_context, _state, feedbackLoopData) => {
  if (feedbackLoopData.actionValue.reaction === 'like') {
    console.log('👍' + ' ' + feedbackLoopData.actionValue.feedback!);
  } else {
    console.log('👎' + ' ' + feedbackLoopData.actionValue.feedback!);
  }
});

app.ai.action<PredictedSayCommand>(AI.SayCommandActionName, async (context, state, data, action) => {
  let activity;
  if (data.response.context && data.response.context.citations.length > 0) {
    const attachment = CardFactory.adaptiveCard(createResponseCard(data.response));
    activity = MessageFactory.attachment(attachment);
  }
  else {
    activity = MessageFactory.text(data.response.content);
  }

  activity.entities = [
    {
      type: "https://schema.org/Message",
      "@type": "Message",
      "@context": "https://schema.org",
      "@id": "",
      // Generated by AI label
      additionalType: ["AIGeneratedContent"],
      // Sensitivity label
      usageInfo: {
        "@type": "CreativeWork",
        name: "Confidential",
        description: "Sensitive information, do not share outside of your organization.",
      }
    },

  ];
  activity.channelData = {
    feedbackLoopEnabled: true
  };

  await context.sendActivity(activity);

  return "success";

});

export default app;